"use strict";

/* Official RustDesk advanced-settings keys for the Config tab catalog.
   https://rustdesk.com/docs/en/self-host/client-configuration/advanced-settings/
   DVForge builds 1.4.9 — keys with min "1.5.0" are listed but marked unusable. */
window.ADVANCED_KEYS = [
  /* ── Security ─────────────────────────────────────────── */
  { group: "Security", key: "access-mode", values: "custom, full, view", def: "custom", sample: "custom", hint: "Incoming permission preset.", owned: "Permissions" },
  { group: "Security", key: "enable-keyboard", values: "Y, N", def: "Y", sample: "N", hint: "Keyboard and mouse for incoming sessions.", owned: "Permissions" },
  { group: "Security", key: "enable-clipboard", values: "Y, N", def: "Y", sample: "N", hint: "Clipboard for incoming sessions.", owned: "Permissions" },
  { group: "Security", key: "enable-file-transfer", values: "Y, N", def: "Y", sample: "N", hint: "File transfer for incoming sessions.", owned: "Permissions" },
  { group: "Security", key: "enable-camera", values: "Y, N", def: "Y", sample: "N", hint: "Camera for incoming sessions.", owned: "Permissions" },
  { group: "Security", key: "enable-terminal", values: "Y, N", def: "Y", sample: "N", hint: "Terminal for incoming sessions.", owned: "Permissions" },
  { group: "Security", key: "enable-remote-printer", values: "Y, N", def: "Y", sample: "N", hint: "Remote printer (Windows).", owned: "Permissions" },
  { group: "Security", key: "enable-audio", values: "Y, N", def: "Y", sample: "N", hint: "Audio capture for incoming sessions.", owned: "Permissions" },
  { group: "Security", key: "enable-tunnel", values: "Y, N", def: "Y", sample: "N", hint: "TCP tunneling.", owned: "Permissions" },
  { group: "Security", key: "enable-remote-restart", values: "Y, N", def: "Y", sample: "N", hint: "Controller can restart this PC.", owned: "Permissions" },
  { group: "Security", key: "enable-record-session", values: "Y, N", def: "Y", sample: "N", hint: "Allow sessions to be recorded.", owned: "Permissions" },
  { group: "Security", key: "enable-block-input", values: "Y, N", def: "Y", sample: "N", hint: "Controller can block local input (Windows).", owned: "Permissions" },
  { group: "Security", key: "allow-remote-config-modification", values: "Y, N", def: "N", sample: "N", hint: "Controller can change Settings on this PC.", owned: "Permissions" },
  { group: "Security", key: "enable-privacy-mode", values: "Y, N", def: "Y", sample: "N", hint: "Allow the controller to blank the local screen. Different from privacy-mode (peer default).", useful: true },
  { group: "Security", key: "enable-lan-discovery", values: "Y, N", def: "Y", sample: "N", hint: "Let LAN peers find this device.", owned: "Tweaks" },
  { group: "Security", key: "direct-server", values: "Y, N", def: "N", sample: "Y", hint: "Enable direct IP access.", owned: "Tweaks" },
  { group: "Security", key: "direct-access-port", values: "port", def: "21118", sample: "21118", hint: "Port for direct IP access.", useful: true },
  { group: "Security", key: "whitelist", values: ", or ip,ip / CIDR", def: ",", sample: "192.168.1.0/24", hint: "Only these IPs can connect in. Comma means no filter.", useful: true },
  { group: "Security", key: "id-whitelist", values: ", or id,id (* ? ok)", def: ",", sample: "123456789", hint: "Only these IDs can connect in. Not a replacement for a password.", min: "1.5.0" },
  { group: "Security", key: "allow-auto-disconnect", values: "Y, N", def: "N", sample: "Y", hint: "Close incoming sessions after idle.", owned: "Tweaks" },
  { group: "Security", key: "auto-disconnect-timeout", values: "minutes", def: "10", sample: "10", hint: "Idle minutes before auto-disconnect.", useful: true },
  { group: "Security", key: "allow-only-conn-window-open", values: "Y, N", def: "N", sample: "Y", hint: "Only accept connections if the RustDesk window is open." },
  { group: "Security", key: "approve-mode", values: "password, click, password-click", def: "password-click", sample: "password", hint: "How incoming connections are accepted.", owned: "Access" },
  { group: "Security", key: "verification-method", values: "use-temporary-password, use-permanent-password, use-both-passwords", def: "use-both-passwords", sample: "use-permanent-password", hint: "Which password types are allowed. Hide-CM forces permanent-only.", owned: "Tweaks" },
  { group: "Security", key: "temporary-password-length", values: "6, 8, 10", def: "6", sample: "8", hint: "Length of the one-time password." },
  { group: "Security", key: "allow-hide-cm", values: "Y, N", def: "N", sample: "Y", hint: "Allow hiding the connection-accept window.", owned: "Tweaks" },
  { group: "Security", key: "proxy-url", values: "http(s)://… or socks5://…", def: "", sample: "socks5://127.0.0.1:1080", hint: "HTTP or SOCKS5 proxy URL." },
  { group: "Security", key: "proxy-username", values: "string", def: "", sample: "user", hint: "Proxy username." },
  { group: "Security", key: "proxy-password", values: "string", def: "", sample: "pass", hint: "Proxy password." },
  { group: "Security", key: "one-way-clipboard-redirection", values: "Y, N", def: "N", sample: "Y", hint: "Block clipboard from the host back to you.", useful: true },
  { group: "Security", key: "one-way-file-transfer", values: "Y, N", def: "N", sample: "Y", hint: "Block file transfer from the host back to you.", useful: true },
  { group: "Security", key: "sync-init-clipboard", values: "Y, N", def: "N", sample: "Y", hint: "Sync clipboard when the session starts (controller → host)." },
  { group: "Security", key: "allow-logon-screen-password", values: "Y, N", def: "N", sample: "Y", hint: "Allow the password at the login / lock screen.", useful: true },
  { group: "Security", key: "enable-trusted-devices", values: "Y, N", def: "Y", sample: "N", hint: "Trusted devices skip 2FA." },
  { group: "Security", key: "allow-numeric-one-time-password", values: "Y, N", def: "N", sample: "Y", hint: "Numeric-only one-time passwords.", min: "1.4.1", pro: true },
  { group: "Security", key: "allow-remote-cm-modification", values: "Y, N", def: "N", sample: "Y", hint: "Controller can click the accept window (permissions, accept)." },
  { group: "Security", key: "enable-perm-change-in-accept-window", values: "Y, N", def: "Y", sample: "N", hint: "User can change permissions in the accept window before connecting." },

  /* ── Already on this tab (top-level custom client) ───── */
  { group: "This tab", key: "password", values: "string", def: "", sample: "", hint: "Preset permanent password for incoming access.", owned: "Access" },
  { group: "This tab", key: "conn-type", values: "incoming, outgoing", def: "both (omit)", sample: "incoming", hint: "incoming = host only, outgoing = controller only. Omit for both.", owned: "Tweaks" },
  { group: "This tab", key: "disable-settings", values: "Y", def: "unset", sample: "Y", hint: "Lock the Settings page entirely.", owned: "Tweaks" },
  { group: "This tab", key: "disable-installation", values: "Y", def: "unset", sample: "Y", hint: "Hide the in-app installer.", owned: "Tweaks" },
  { group: "This tab", key: "app-name", values: "string", def: "", sample: "", hint: "Shown name inside the client.", owned: "Identity" },

  /* ── General ──────────────────────────────────────────── */
  { group: "General", key: "theme", values: "dark, light, system", def: "system", sample: "dark", hint: "UI theme. Use Theme → Apply as Override to lock it.", owned: "Theme" },
  { group: "General", key: "lang", values: "default, en, nl, fr, de, zh-cn, …", def: "default", sample: "en", hint: "Client language." },
  { group: "General", key: "allow-auto-record-incoming", values: "Y, N", def: "N", sample: "Y", hint: "Automatically record incoming sessions." },
  { group: "General", key: "allow-auto-record-outgoing", values: "Y, N", def: "N", sample: "Y", hint: "Automatically record outgoing sessions." },
  { group: "General", key: "hide-recording-button", values: "Y, N", def: "N", sample: "Y", hint: "Hide the in-session Record button (recording can still run).", useful: true },
  { group: "General", key: "video-save-directory", values: "path", def: "Videos/app", sample: "", hint: "Where recorded videos are saved." },
  { group: "General", key: "windows-service-video-save-directory", values: "absolute Windows path", def: "ProgramData\\app\\recording", sample: "D:\\RustDesk\\recordings", hint: "Recording folder when running as a Windows service." },
  { group: "General", key: "allow-auto-update", values: "Y, N", def: "N", sample: "N", hint: "Auto-update from GitHub (Windows, not outgoing-only).", min: "1.4.6" },
  { group: "General", key: "enable-confirm-closing-tabs", values: "Y, N", def: "Y", sample: "N", hint: "Confirm before closing multiple remote tabs." },
  { group: "General", key: "enable-abr", values: "Y, N", def: "Y", sample: "Y", hint: "Adaptive bitrate." },
  { group: "General", key: "allow-remove-wallpaper", values: "Y, N", def: "N", sample: "Y", hint: "Remove wallpaper during incoming sessions.", owned: "Tweaks" },
  { group: "General", key: "enable-open-new-connections-in-tabs", values: "Y, N", def: "Y", sample: "N", hint: "Open new connections in a tab instead of a window." },
  { group: "General", key: "allow-always-software-render", values: "Y, N", def: "N", sample: "Y", hint: "Always use software rendering." },
  { group: "General", key: "enable-hwcodec", values: "Y, N", def: "Y", sample: "Y", hint: "Hardware video encoding." },
  { group: "General", key: "peer-card-ui-type", values: "0 big, 1 small, 2 list", def: "0", sample: "2", hint: "Peer list layout." },
  { group: "General", key: "peer-sorting", values: "Remote ID, Remote Host, Username", def: "Remote ID", sample: "Remote ID", hint: "Peer list sort order." },
  { group: "General", key: "sync-ab-with-recent-sessions", values: "Y, N", def: "N", sample: "Y", hint: "Sync address book with recent sessions." },
  { group: "General", key: "sync-ab-tags", values: "Y, N", def: "N", sample: "Y", hint: "Sort address-book tags." },
  { group: "General", key: "filter-ab-by-intersection", values: "Y, N", def: "N", sample: "Y", hint: "Filter address book by tag intersection." },
  { group: "General", key: "use-texture-render", values: "Y, N", def: "OS-dependent", sample: "Y", hint: "Texture render (desktop). Disable if the picture glitches." },
  { group: "General", key: "enable-udp-punch", values: "Y, N", def: "Y", sample: "N", hint: "UDP hole punching.", min: "1.4.1" },
  { group: "General", key: "enable-ipv6-punch", values: "Y, N", def: "N on self-host", sample: "N", hint: "IPv6 P2P.", min: "1.4.1" },

  /* ── Display (per-peer defaults) ─────────────────────── */
  { group: "Display", key: "view-only", values: "Y, N", def: "N", sample: "N", hint: "Default view-only for new peers." },
  { group: "Display", key: "show-monitors-toolbar", values: "Y, N", def: "N", sample: "Y", hint: "Show monitors in the toolbar." },
  { group: "Display", key: "collapse-toolbar", values: "Y, N", def: "N", sample: "Y", hint: "Collapse the remote toolbar after connect." },
  { group: "Display", key: "show-remote-cursor", values: "Y, N", def: "N", sample: "Y", hint: "Show the remote cursor." },
  { group: "Display", key: "follow-remote-cursor", values: "Y, N", def: "N", sample: "Y", hint: "Follow the remote cursor." },
  { group: "Display", key: "follow-remote-window", values: "Y, N", def: "N", sample: "Y", hint: "Follow remote window focus." },
  { group: "Display", key: "zoom-cursor", values: "Y, N", def: "N", sample: "Y", hint: "Scale the cursor with the image." },
  { group: "Display", key: "show-quality-monitor", values: "Y, N", def: "N", sample: "Y", hint: "Show the quality monitor overlay." },
  { group: "Display", key: "disable-audio", values: "Y, N", def: "N", sample: "Y", hint: "Mute on the controller side (not the same as enable-audio)." },
  { group: "Display", key: "enable-file-copy-paste", values: "Y, N", def: "N", sample: "Y", hint: "File copy-paste in the session (Windows)." },
  { group: "Display", key: "disable-clipboard", values: "Y, N", def: "N", sample: "Y", hint: "Disable text clipboard on the controller side." },
  { group: "Display", key: "lock-after-session-end", values: "Y, N", def: "N", sample: "Y", hint: "Lock the remote PC when you disconnect.", useful: true },
  { group: "Display", key: "privacy-mode", values: "Y, N", def: "N", sample: "Y", hint: "Start new peers in privacy mode. Different from enable-privacy-mode." },
  { group: "Display", key: "i444", values: "Y, N", def: "N", sample: "Y", hint: "True color (4:4:4)." },
  { group: "Display", key: "reverse-mouse-wheel", values: "Y, N", def: "N", sample: "Y", hint: "Reverse mouse wheel." },
  { group: "Display", key: "swap-left-right-mouse", values: "Y, N", def: "N", sample: "Y", hint: "Swap left/right mouse buttons." },
  { group: "Display", key: "displays-as-individual-windows", values: "Y, N", def: "N", sample: "Y", hint: "Each remote display in its own window." },
  { group: "Display", key: "use-all-my-displays-for-the-remote-session", values: "Y, N", def: "N", sample: "Y", hint: "Use all local displays for the remote session." },
  { group: "Display", key: "view-style", values: "original, adaptive", def: "original", sample: "adaptive", hint: "Default view style." },
  { group: "Display", key: "scroll-style", values: "scrollauto, scrollbar, scrolledge", def: "scrollauto", sample: "scrollauto", hint: "Default scroll style. scrolledge needs 1.4.4+." },
  { group: "Display", key: "edge-scroll-edge-thickness", values: "20–150", def: "100", sample: "100", hint: "Edge thickness when scroll-style=scrolledge.", min: "1.4.4" },
  { group: "Display", key: "image-quality", values: "best, balanced, low, custom", def: "balanced", sample: "balanced", hint: "Default image quality." },
  { group: "Display", key: "custom-image-quality", values: "10–2000", def: "50", sample: "50", hint: "Quality when image-quality=custom." },
  { group: "Display", key: "custom-fps", values: "5–120", def: "30", sample: "30", hint: "FPS when image-quality=custom." },
  { group: "Display", key: "codec-preference", values: "auto, vp8, vp9, av1, h264, h265", def: "auto", sample: "auto", hint: "Default codec. Other than vp8/vp9 may fail on some machines." },
  { group: "Display", key: "terminal-persistent", values: "Y, N", def: "N", sample: "Y", hint: "Keep terminal sessions after disconnect." },
  { group: "Display", key: "trackpad-speed", values: "10–1000", def: "100", sample: "100", hint: "Default trackpad speed." },
  { group: "Display", key: "touch-mode", values: "Y, N", def: "N", sample: "Y", hint: "Touch mode vs mouse mode. On 1.4.3+ this overrides per-peer." },

  /* ── Lock-down ───────────────────────────────────────── */
  { group: "Lock-down", key: "disable-change-permanent-password", values: "Y, N", def: "N", sample: "Y", hint: "User cannot change the permanent password.", useful: true, min: "1.4.5" },
  { group: "Lock-down", key: "disable-change-id", values: "Y, N", def: "N", sample: "Y", hint: "User cannot change the device ID.", min: "1.4.5" },
  { group: "Lock-down", key: "disable-unlock-pin", values: "Y, N", def: "N", sample: "Y", hint: "Unlocking Settings requires admin, even if a PIN is set.", min: "1.4.5" },
  { group: "Lock-down", key: "hide-stop-service", values: "Y, N", def: "N", sample: "Y", hint: "Hide Stop service while the service is running.", useful: true },
  { group: "Lock-down", key: "hide-tray", values: "Y, N", def: "N", sample: "Y", hint: "Hide the systray icon.", useful: true },
  { group: "Lock-down", key: "hide-security-settings", values: "Y, N", def: "N", sample: "Y", hint: "Hide the Security tab. Settings page must stay allowed.", useful: true },
  { group: "Lock-down", key: "hide-network-settings", values: "Y, N", def: "N", sample: "Y", hint: "Hide the Network tab. Settings page must stay allowed." },
  { group: "Lock-down", key: "hide-server-settings", values: "Y, N", def: "N", sample: "Y", hint: "Hide server settings. Settings page must stay allowed." },
  { group: "Lock-down", key: "hide-proxy-settings", values: "Y, N", def: "N", sample: "Y", hint: "Hide proxy settings." },
  { group: "Lock-down", key: "hide-websocket-settings", values: "Y, N", def: "N", sample: "Y", hint: "Hide websocket settings." },
  { group: "Lock-down", key: "hide-remote-printer-settings", values: "Y, N", def: "N", sample: "Y", hint: "Hide remote printer settings." },
  { group: "Lock-down", key: "hide-general-settings", values: "Y, N", def: "N", sample: "Y", hint: "Hide the General tab (works even when Settings are disabled).", min: "1.5.0" },
  { group: "Lock-down", key: "hide-username-on-card", values: "Y, N", def: "N", sample: "Y", hint: "Hide username on peer cards." },
  { group: "Lock-down", key: "hide-help-cards", values: "Y, N", def: "N", sample: "Y", hint: "Hide UAC / permission warning cards." },
  { group: "Lock-down", key: "disable-group-panel", values: "Y, N", def: "N", sample: "Y", hint: "Hide the Accessible devices panel." },
  { group: "Lock-down", key: "disable-discovery-panel", values: "Y, N", def: "N", sample: "Y", hint: "Hide the Discovered panel." },
  { group: "Lock-down", key: "remove-preset-password-warning", values: "Y, N", def: "Y", sample: "Y", hint: "Hide the GUI warning when a preset password is baked in." },
  { group: "Lock-down", key: "allow-command-line-settings-when-settings-disabled", values: "Y, N", def: "N", sample: "Y", hint: "CLI can still change settings when the Settings UI is locked.", min: "1.4.7" },
  { group: "Lock-down", key: "pre-elevate-service", values: "Y, N", def: "N", sample: "Y", hint: "Auto-elevate Windows portable on run." },

  /* ── Network extra ───────────────────────────────────── */
  { group: "Network", key: "relay-server", values: "host:port", def: "(inferred)", sample: "", hint: "Explicit hbbr relay. Usually leave blank." },
  { group: "Network", key: "disable-udp", values: "Y, N", def: "N", sample: "Y", hint: "TCP only — do not use UDP 21116." },
  { group: "Network", key: "allow-websocket", values: "Y, N", def: "N", sample: "Y", hint: "WebSocket to the server (relay only).", min: "1.4.0", pro: true },
  { group: "Network", key: "allow-https-21114", values: "Y, N", def: "N", sample: "Y", hint: "Allow HTTPS API on port 21114.", min: "1.3.9" },
  { group: "Network", key: "allow-insecure-tls-fallback", values: "Y, N", def: "N", sample: "Y", hint: "Skip TLS cert check if verification fails.", min: "1.4.4" },
  { group: "Network", key: "allow-hostname-as-id", values: "Y, N", def: "N", sample: "Y", hint: "Use hostname as ID on first run.", min: "1.4.0" },

  /* ── Pro ─────────────────────────────────────────────── */
  { group: "Pro", key: "default-connect-password", values: "string", def: "", sample: "", hint: "Password this client uses when connecting OUT. Not the incoming password.", useful: true },
  { group: "Pro", key: "display-name", values: "string", def: "OS user", sample: "", hint: "Name shown on the remote accept popup." },
  { group: "Pro", key: "allow-ask-for-note", values: "Y, N", def: "N", sample: "Y", hint: "Ask for a note when a session ends.", min: "1.4.4" },
  { group: "Pro", key: "preset-address-book-name", values: "string", def: "", sample: "", hint: "Auto-assign this device to an address book.", pro: true },
  { group: "Pro", key: "preset-address-book-tag", values: "string", def: "", sample: "", hint: "Address-book tag.", pro: true },
  { group: "Pro", key: "preset-address-book-alias", values: "string", def: "", sample: "", hint: "Device alias in the address book.", pro: true, min: "1.4.3" },
  { group: "Pro", key: "preset-address-book-password", values: "string", def: "", sample: "", hint: "Device password in the address book.", pro: true, min: "1.4.3" },
  { group: "Pro", key: "preset-address-book-note", values: "string", def: "", sample: "", hint: "Device note in the address book.", pro: true, min: "1.4.3" },
  { group: "Pro", key: "preset-user-name", values: "string", def: "", sample: "", hint: "Assign this device to a Pro user.", pro: true },
  { group: "Pro", key: "preset-strategy-name", values: "string", def: "", sample: "", hint: "Assign a Pro strategy.", pro: true },
  { group: "Pro", key: "preset-device-group-name", values: "string", def: "", sample: "", hint: "Assign a device group.", pro: true, min: "1.3.8" },
  { group: "Pro", key: "preset-device-username", values: "string", def: "", sample: "", hint: "Preset OS username shown in console.", pro: true, min: "1.4.3" },
  { group: "Pro", key: "preset-device-name", values: "string", def: "", sample: "", hint: "Preset hostname shown in console.", pro: true, min: "1.4.3" },
  { group: "Pro", key: "preset-note", values: "string", def: "", sample: "", hint: "Preset device note in console.", pro: true, min: "1.4.3" },
  { group: "Pro", key: "register-device", values: "Y, N", def: "Y", sample: "N", hint: "N = do not show this device in the Pro console (custom2 license).", pro: true },

  /* ── Android ─────────────────────────────────────────── */
  { group: "Android", key: "disable-floating-window", values: "Y, N", def: "N", sample: "N", hint: "Leave N. The bubble keeps Android from killing the service." },
  { group: "Android", key: "floating-window-size", values: "32–320", def: "120", sample: "120", hint: "Floating window size. Below 120 is hard to tap." },
  { group: "Android", key: "floating-window-untouchable", values: "Y, N", def: "N", sample: "Y", hint: "Touches pass through the floating window." },
  { group: "Android", key: "floating-window-transparency", values: "0–10", def: "10", sample: "0", hint: "0 = invisible bubble that still keeps the service alive.", useful: true },
  { group: "Android", key: "floating-window-svg", values: "one-line SVG", def: "app icon", sample: "", hint: "Custom SVG for the floating window, as one line." },
  { group: "Android", key: "keep-screen-on", values: "never, during-controlled, service-on", def: "during-controlled", sample: "during-controlled", hint: "When the Android screen stays awake.", useful: true },
  { group: "Android", key: "keep-awake-during-incoming-sessions", values: "Y, N", def: "Y", sample: "Y", hint: "Keep the screen awake during incoming sessions." },
  { group: "Android", key: "keep-awake-during-outgoing-sessions", values: "Y, N", def: "Y", sample: "Y", hint: "Keep the screen awake during outgoing sessions." },
  { group: "Android", key: "enable-android-software-encoding-half-scale", values: "Y, N", def: "Y", sample: "Y", hint: "Half-res software encoding above 1200px." },
  { group: "Android", key: "show-virtual-mouse", values: "Y, N", def: "N", sample: "Y", hint: "Virtual mouse when controlling desktop from a phone. Use Default, not Override.", min: "1.4.3" },
  { group: "Android", key: "show-virtual-joystick", values: "Y, N", def: "N", sample: "Y", hint: "Virtual joystick (needs show-virtual-mouse). Use Default, not Override.", min: "1.4.3" },

  /* ── Windows / other ─────────────────────────────────── */
  { group: "Windows", key: "enable-directx-capture", values: "Y, N", def: "Y", sample: "Y", hint: "Prefer DirectX capture over GDI." },
  { group: "Windows", key: "allow-d3d-render", values: "Y, N", def: "N", sample: "Y", hint: "D3D render (higher FPS; can go black on some GPUs).", min: "1.3.9" },
  { group: "Windows", key: "main-window-always-on-top", values: "Y, N", def: "N", sample: "Y", hint: "Keep the main window on top.", min: "1.4.2" },
];
